name: PXC Unit Tests v8
run-name: PXC unit tests triggered by ${{ github.sha }}
on:
  push
jobs:
  unit-test-auto-tune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: src/github.com/cloudfoundry-incubator/switchboard/go.mod
      - uses: actions/setup-ruby@v1
      - run: scripts/test-unit
