name: PXC Unit Tests v15
run-name: unit tests for pr "${{ github.event.pull_request.title }}" (branch ${{ github.head_ref }})
on:
  pull_request
permissions:
  contents: read
jobs:
  pxc-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ oldstable, stable ]
    name: unit tests (go "${{ matrix.version }}" version)
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
      - uses: actions/setup-ruby@v1
      - run: go version
      - run: scripts/test-unit
