name: Automated Unit Tests v17
run-name: 'unit tests: PR #${{ github.event.number }} "${{ github.event.pull_request.title }}"'
on:
  pull_request
permissions:
  contents: read
jobs:
  pxc-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ oldstable, stable ]
    name: go "${{ matrix.version }}" version
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
      - uses: actions/setup-ruby@v1
      - run: go version
      - run: scripts/test-unit
